
language: node_js
branches:
  only:
  - development
node_js:
  - '9'
  - '8'
  - node
install:
- npm install -g travis-ci-cloudfront-invalidation
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: 'seafood-fest-serverless'
  local_dir: build
  skip_cleanup: true
  on:
    branch: development
